TraVis: use `adb shell ps` instead of `adb jdwp`
The JDWP number is a pid of the target app. We now use the device's `ps`
command to extract the pid using the process name. This should be more
reliable and quicker than the buggy `adb jdwp` command.

This change also allows the process name (:suffix) to be specified in
the component name (see the Facebook examples).

diff --git a/tools/jitana-travis/scripts/launch b/tools/jitana-travis/scripts/launch
--- a/tools/jitana-travis/scripts/launch
+++ b/tools/jitana-travis/scripts/launch
@@ -2,16 +2,20 @@
 
 # Get this by:
 #    aapt dump xmltree foo.apk AndroidManifest.xml
-# COMPONENT=jp.bio100.android.superdepth/.SuperDepth
-COMPONENT=com.johnemulators.johnneslite/.MainActivity
-# COMPONENT=com.facebook.katana/.LoginActivity
-# COMPONENT=com.facebook.katana/com.facebook.dash.activities.DashActivity
-# COMPONENT=com.example.dragon/.MainActivity
-# COMPONENT=net.mandaria.tippytipper/net.mandaria.tippytipperlibrary.activities.TippyTipper
-# COMPONENT=com.google.earth/.EarthActivity
-# COMPONENT=com.android.deskclock/.DeskClock
-# COMPONENT=com.instagram.android/.activity.MainTabActivity
+# component=jp.bio100.android.superdepth/.SuperDepth
+# component=com.johnemulators.johnneslite/.MainActivity
+# component=com.facebook.katana:nodex/.LoginActivity
+# component=com.facebook.katana:dash/com.facebook.dash.activities.DashActivity
+# component=com.example.dragon/.MainActivity
+# component=net.mandaria.tippytipper/net.mandaria.tippytipperlibrary.activities.TippyTipper
+component=com.google.earth/.EarthActivity
+# component=com.android.deskclock/.DeskClock
+# component=com.instagram.android/.activity.MainTabActivity
 
+proc_name=${component%%/*}
+component=${proc_name%:*}/${component##*/}
+
+echo "Waiting for the device..."
 adb wait-for-device
 
 # Make sure the screen is on.
@@ -19,18 +23,16 @@ adb shell dumpsys power | grep "mScreenOn=true" \
     | xargs -0 test -z && adb shell input keyevent 26 && adb shell input keyevent 82
 
 # Start the app by sending an explicit intent.
-adb shell am start -S -n $COMPONENT -D
-
-sleep 2
-
-# Extract the JDWP port number. This avoids the adb jdwp freeze bug.
-rm -rf jdwp_ports.txt
-bash -c '(sleep 1; kill -9 $$) & exec adb jdwp > jdwp_ports.txt'
-JDWP_PORT=`tail -1 jdwp_ports.txt`
-echo "JDWP_PORT: $JDWP_PORT"
+adb shell am start -S -n $component -D
 
 # Port forward.
-adb forward --remove-all && adb -d forward tcp:6100 jdwp:$JDWP_PORT
+jdwp_pid=`adb shell ps | awk '$9 == "'$proc_name'\r" { print $2 }'`
+if [[ -z "$jdwp_pid" ]]; then
+    echo "Error: failed to find the PID"
+    exit 1
+fi
+echo "jdwp_pid: $jdwp_pid"
+adb forward --remove-all && adb -d forward tcp:6100 jdwp:$jdwp_pid
 
 # Start Jitana in the background.
 # rm -rf output/insn/*.dot
@@ -38,19 +40,19 @@ mkdir -p output/insn
 
 if [[ "$1" == "monkey" ]]; then
     ./jitana-travis &
-    JITANA_PID=$!
+    jitana_pid=$!
 
     sleep 5
 
     # Start Monkey.
     echo "=== Monky: started ============================"
-    time adb shell monkey -p ${COMPONENT%%/*} 3000
+    time adb shell monkey -p ${component%%/*} 3000
     echo "=== Monky: stopped ============================"
 
     # Kill Jitana.
     echo "Killing Jitana in 5 seconds..."
     sleep 5
-    kill -INT $JITANA_PID
+    kill -INT $jitana_pid
     wait
     echo "Done."
 else
